### ISSUE TITLE
Re-enable rate-later list interface

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#70]

**Comment by amatissart** [comment]
After some exploration, the scope of the issue is now clearer to me.  
Here is my work branch: https://github.com/tournesol-app/tournesol-frontend/compare/enable-rate-rater-list 
(Nothing fancy for now, still a lot of commented code, and no API integration).

I have a few questions before going further:
* On my branch, I re-activated the Router and some of the existing routes: Home(`/`) and `/rate_later` routes.  
Are there other routes that should be enabled at this stage?
* The authentication relies currently on global variables (`window.is_authenticated`, `window.user_information_id`, etc.) probably for development purposes. Should we keep it as-is for now ?
* The original projet uses code generated from the OpenAPI schema to implement the API client. Any opinion about using the same approach with the new backend ?

Also, I see that @jstainer-kleis started a [brand new branch "reboot"](https://github.com/tournesol-app/tournesol-frontend/tree/reboot) that addresses some of these points. Perhaps that's the approach we want to take?
